## We will learn about Word Embedding.. Let's go

#### Word Embedding works as follows:
    vocab size
    one_hot function
    pass that to embeding layer
    initialize the dimensions

In [1]:
from keras.preprocessing.text import one_hot

In [10]:
sentences = ['he is a nice guy, I know him since 2008',
             'she is a nice lady, her house is few yards away from mine',
             'would you like to eat apple?',
             'did you eat orange from fridge?',
            'this is the best place to eat in Paris.',
             'munich is a must visit destination',
            "i have not seen this view in my life, of it's so beautiful",
            'amazing scenery,loved it']

In [11]:
sentences

['he is a nice guy, I know him since 2008',
 'she is a nice lady, her house is few yards away from mine',
 'would you like to eat apple?',
 'did you eat orange from fridge?',
 'this is the best place to eat in Paris.',
 'munich is a must visit destination',
 "i have not seen this view in my life, of it's so beautiful",
 'amazing scenery,loved it']

In [12]:
vocab_size = 5000

### One hot representation

In [13]:
onehot_phase = [one_hot(words,vocab_size) for words in sentences]
print(onehot_phase)

[[1851, 1975, 2130, 3373, 2059, 1955, 3109, 1026, 4322, 4128], [4733, 1975, 2130, 3373, 2705, 3988, 1739, 1975, 2534, 3838, 3214, 3588, 4754], [1398, 1142, 494, 2324, 999, 471], [2240, 1142, 999, 2488, 3588, 4722], [58, 1975, 136, 2640, 2351, 2324, 999, 463, 3888], [246, 1975, 2130, 1455, 1533, 1348], [1955, 2516, 1000, 4448, 58, 1644, 463, 99, 2502, 4080, 3227, 3337, 1749], [2659, 554, 2808, 3369]]


## Word embedding representation

In [9]:
from keras.layers import Embedding
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
import numpy as np

In [15]:
#make all the length same, so using padding
sent_length = 10
embed_doc = pad_sequences(onehot_phase,padding='pre',maxlen=sent_length)
print(embed_doc)

[[1851 1975 2130 3373 2059 1955 3109 1026 4322 4128]
 [3373 2705 3988 1739 1975 2534 3838 3214 3588 4754]
 [   0    0    0    0 1398 1142  494 2324  999  471]
 [   0    0    0    0 2240 1142  999 2488 3588 4722]
 [   0   58 1975  136 2640 2351 2324  999  463 3888]
 [   0    0    0    0  246 1975 2130 1455 1533 1348]
 [4448   58 1644  463   99 2502 4080 3227 3337 1749]
 [   0    0    0    0    0    0 2659  554 2808 3369]]


In [22]:
dim = 30
model = Sequential()
model.add(Embedding(vocab_size,40,input_length=sent_length))
model.compile('adam','mse')
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_6 (Embedding)      (None, 10, 40)            200000    
Total params: 200,000
Trainable params: 200,000
Non-trainable params: 0
_________________________________________________________________


In [23]:
pred = model.predict(embed_doc)

In [27]:
print(pred)

[[[-0.02314206 -0.03284391 -0.00875656 ... -0.03712809  0.00425158
    0.03065208]
  [-0.00119698  0.04100497  0.03721508 ... -0.04978296 -0.03678153
   -0.02506827]
  [ 0.04548771  0.03767608 -0.04884445 ...  0.00629044 -0.03002136
   -0.03922911]
  ...
  [ 0.03579644  0.04790806 -0.02466181 ...  0.02136889  0.01905732
    0.019267  ]
  [-0.00920749 -0.0363327   0.00170294 ...  0.04563563 -0.03359319
    0.04253446]
  [ 0.03922819 -0.00402929 -0.0146381  ... -0.0423959   0.01512141
   -0.00047395]]

 [[-0.02343982  0.04148278 -0.00523537 ... -0.04410718 -0.01251819
    0.02491378]
  [-0.00946444  0.0473675   0.00676442 ... -0.04946276 -0.00398868
    0.02164209]
  [ 0.00146062 -0.02973489  0.00639034 ... -0.00733173 -0.04820502
   -0.01146611]
  ...
  [-0.03123596  0.04161916  0.02428602 ... -0.04192383 -0.0224188
    0.03470184]
  [-0.01065604  0.02878845 -0.00170624 ...  0.00450091 -0.00275477
    0.0113587 ]
  [ 0.03782446  0.02640004  0.03192264 ...  0.0049045  -0.04352292
    0.0

In [29]:
embed_doc[1]

array([3373, 2705, 3988, 1739, 1975, 2534, 3838, 3214, 3588, 4754],
      dtype=int32)

In [30]:
print(model.predict(embed_doc)[1])

[[-0.02343982  0.04148278 -0.00523537  0.01024264  0.00710701  0.02832371
  -0.03328086  0.03953998 -0.03066577  0.04064207  0.04200916  0.04028739
  -0.01407021 -0.0004262  -0.0139529   0.02207157 -0.04898958 -0.02997303
   0.03715879  0.01866441  0.00287018 -0.02412244 -0.03893179  0.01912901
  -0.03194914  0.0393564  -0.04317414 -0.00742326 -0.00592982 -0.04415678
   0.02864686  0.04870101 -0.01110341  0.01295393  0.00384592  0.04735818
   0.00814656 -0.04410718 -0.01251819  0.02491378]
 [-0.00946444  0.0473675   0.00676442 -0.04326059 -0.04378578  0.02225456
  -0.02166237 -0.0035326  -0.01420487 -0.0303211   0.0251686  -0.02765889
   0.02699541 -0.04327524  0.03447571 -0.00575013  0.01486592  0.03592808
   0.0392389   0.03245032 -0.0372646  -0.04414171 -0.0403981   0.04406071
  -0.00941211 -0.00195331  0.00415111 -0.00748652  0.03903325 -0.02944331
   0.00067676  0.01832796 -0.00674659 -0.03122271  0.00102091  0.01463821
   0.03608802 -0.04946276 -0.00398868  0.02164209]
 [ 0.00146

### so this is how the word embedding can be explained and how the dimension is getting changed that also explained